name: Portfolio Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.X]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: npm install && npm audit fix --force && npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: build
